version: '3'

services:
  backend:  # Define your backend service here
    build: .
    links:
      - elk
      - db
      - mail
    ports:
      - "8181:80"
    extra_hosts:
      - "web:127.0.0.1"
      
  elk:
    image: elasticsearch:2.2

  db:
    image: postgres
    environment:
      - POSTGRES_DB=openloyalty
      - POSTGRES_USER=openloyalty
      - POSTGRES_PASSWORD=openloyalty

  mail:
    image: mailhog/mailhog
    ports:
      - "8186:8025"
